apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercadona-eanboris
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mercadona-eanboris
  template:
    metadata:
      labels:
        app: mercadona-eanboris
    spec:
      containers:
        - name: mercadona-eanboris
          image: localhost:5000/mercadona-eanboris:5
          imagePullPolicy: Never
          ports:
            - containerPort: 8080